config/routes.rb
Hackboard::Application.routes.draw do
  get "comments/create"

  get "users/show"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :pins do
    resources :comments, only: :create
  end

  resources :boards

  resources :users, only: [:show] do
    resources :boards, only: [:index], controller: 'users/boards'
  end

  root to: 'pins#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :pins

  attr_accessible :name, :description, :user_id

  delegate :name, :image_url, to: :user, prefix: true

  validates :name, presence: true
  validates :user, presence: true

  def cover
    pin = pins.latest.first

    pin && pin.image
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user

  attr_accessible :body, :pin

  validates :user, presence: true
  validates :pin, presence: true

  delegate :name, :image_url, to: :user, prefix: true
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board
  has_many :comments
  attr_accessible :description, :image, :url, :board_id

  has_attached_file :image, styles: {default: '200', full: '600'}

  delegate :name, to: :board, prefix: true
  delegate :user, to: :board
  delegate :name, :image_url, to: :user, prefix: true

  validates :board, presence: true
  validates :image, presence: true

  def self.latest
    order("updated_at DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable

  has_many :boards
  has_many :pins, through: :boards
  has_many :comments

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.nickname = auth.info.nickname
      user.name = auth.info.name
      user.image_url = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def owns?(object)
    object.user == self if object.respond_to?(:user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html, :json

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!

  def create
    pin = Pin.find(params[:pin_id])

    if current_user.comments.create(params[:comment].merge(pin: pin))
      redirect_to pin, notice: "Comment created successfully"
    else
      redirect_to pin
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html, :json

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.latest

    respond_with @pins
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.includes(:comments).find(params[:id])

    respond_with @pin
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_with @pin
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to root_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/boards_controller.rb
class Users::BoardsController < ApplicationController

  def index
    user = User.find(params[:user_id])

    @boards = user.boards
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.includes(boards: :pins).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def i_own?(object)
    user_signed_in? && current_user.owns?(object)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/boards/_board.html.erb
<%= link_to board, class: 'col span3 centered' do %>
  <h4><%= board.name %></h4>
  <h4><small><%= pluralize board.pins.count, "pin" %></small></h4>
  <%= image_tag board.cover if board.cover %>
<% end %>

app/views/boards/_empty.html.erb
<div class="well">
  <h3>You have no pins for this board yet</h3>
  <%= render "shared/add_pin" %>
</div>

app/views/boards/_form.html.erb
<%= simple_form_for(@board, html: {class: 'form-horizontal'}) do |f| %>

  <%= f.input :name, input_html: {class: 'input-xlarge'} %>
  <%= f.input :description, input_html: {class: 'input-xxlarge', rows: 6} %>

  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', root_path %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit board / <small><%= @board.name %></small</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render @boards %>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

app/views/boards/show.html.erb
<section class="board-header">
  <h1><%= @board.name %></h1>
</section>

<section class="board-meta row clearfix">
  <%= link_to @board.user, class: 'span3 board-user pull-left' do %>
    <%= image_tag @board.user_image_url %>
    <%= content_tag :span, @board.user_name %>
  <% end %>

  <%= link_to "Edit", edit_board_path(@board), class: 'span1 offset2 board-edit-link btn' if i_own?(@board) %>

  <span class="pull-right board-info"><%= pluralize @board.pins.count, "pin" %></span>
</section>

<%= render layout: 'layouts/pins' do %>
  <%= render(@board.pins) || render("empty") %>
<% end %>

app/views/comments/_comment.html.erb
<%= content_tag_for :div, comment, class: 'clearfix' do %>
  <%= image_tag comment.user_image_url, class: 'pull-left' %>
  <small class="pull-right"><%= time_ago_in_words(comment.created_at) %> ago</small>
  <%= link_to comment.user_name, comment.user %>
  <%= comment.body %>
<% end %>

app/views/layouts/_pins.html.erb
<div class="pins clearfix">
  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Hackeryou :: Hackboard</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Hackboard", root_path, class: 'brand' %>

        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown divider-vertical">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-plus"></i>Add...
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li><%= link_to "A Post", new_pin_path %></li>
                <li><%= link_to "A Board", new_board_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a class="dropdown-toggle user-menu-image" data-toggle="dropdown" href="#"><%= image_tag current_user.image_url %></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= render "/shared/messages" unless flash.empty? %>
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/pins/_empty.html.erb
<div class="well">
  <h3>Oh nooooos...  There are no pins yet!</h3>
  <%= render "shared/add_pin" if user_signed_in? %>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: 'form-horizontal', multipart: true}) do |f| %>
  <%= f.input :image %>
  <%= f.input :description, input_html: {rows: 4} %>
  <%= f.association :board, collection: current_user.boards %>

  <div class="form-actions">
    <%= f.submit "Create Post", class: 'btn btn-primary' %>
    <%= link_to 'Back', pins_path %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<%= content_tag_for :div, pin, class: 'mason col span3' do %>
  <%= link_to pin do %>
    <%= image_tag pin.image.url(:default) %>
    <p class="description"><%= pin.description %></p>
  <% end %>

  <div class="attribution clearfix">
    <%= image_tag pin.user_image_url, class: 'pull-left' %>
    <%= link_to pin.user_name, pin.user %> onto <%= link_to pin.board_name, pin.board %>
  </div>

  <section class="comments clearfox">
    <%= render pin.comments %>
  </section>

  <% if i_own?(pin) %>
    <%= link_to 'Edit', edit_pin_path(pin), class: 'edit btn btn-mini' %>
    <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete btn btn-mini' %>
  <% end %>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/pins/index.html.erb
<% if !user_signed_in? %>
  <div class="signup hero-unit well">
    <h2>Sign in with...</h2>
    <%= link_to user_omniauth_authorize_path(:twitter), class: 'big-button twitter' do %>
      <span class="logo"></span> Twitter
    <% end %>
  </div>
<% end %>

<%= render layout: 'layouts/pins' do %>
  <%= render(@pins) || render("empty") %>
<% end %>

app/views/pins/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/pins/show.html.erb
<%= content_tag_for :div, @pin, class: 'show clearfix' do %>
  <section class="pinner">
    <%= image_tag @pin.user_image_url, class: 'pull-left user-image' %>
    <h4>
      <%= link_to @pin.user_name, @pin.user %><br>
      <small>Posted <%= time_ago_in_words(@pin.created_at) %> ago on <%= link_to @pin.board_name, @pin.board %></small>
    </h4>
  </section>

  <section class="pin-image centered">
    <%= image_tag @pin.image %>
  </section>

  <% if user_signed_in? %>
    <section class="comment clearfix">
      <%= image_tag current_user.image_url, class: 'pull-left user-image' %>
      <%= simple_form_for [@pin, Comment.new] do |f| %>
        <%= f.input :body, wrapper: :append, label: false do %>
          <%= f.input_field :body, placeholder: "Add a comment...", class: "span5" %>
          <%= f.submit "comment", class: 'btn' %>
        <% end %>
      <% end %>
    </section>
  <% end %>

  <section class="comments clearfox">
    <%= render @pin.comments %>
  </section>
<% end %>

app/views/shared/_add_pin.html.erb
<%= link_to "Upload One from your computer", new_pin_path, class: 'btn btn-primary' %>

app/views/shared/_messages.html.erb
<%= content_tag(:div, class: 'alert alert-success') do %>
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
<% end if flash[:notice].present? %>

<%= content_tag(:div, class: 'alert alert-error') do %>
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= alert %>
<% end if flash[:alert].present? %>

app/views/users/boards/index.html.erb
<%= render @boards %>

app/views/users/pins/index.html.erb
<%= render @pins %>

app/views/users/show.html.erb
<div class="well">
  <%= image_tag @user.image_url, class: 'pull-left' %>
  <h2 class="centered"><%= @user.name %></h2>
</div>

<div class="well clearfix">
  <%= render @user.boards %>
</div>